// production.js
module.exports = {
  MONGO_URI: process.env.MONGO_URI_PRODUCTION,
  JWT_SECRET: process.env.JWT_SECRET_PRODUCTION,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY_PRODUCTION,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID_PRODUCTION,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID_PRODUCTION,
  SENTRY_DSN: process.env.SENTRY_DSN_PRODUCTION,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME_PRODUCTION,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY_PRODUCTION,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET_PRODUCTION,
  REDIS_HOST: process.env.REDIS_HOST_PRODUCTION,
  REDIS_PORT: process.env.REDIS_PORT_PRODUCTION,
  NODE_ENV: "production",
  PORT: process.env.PORT || 80,
};
